[features]
seeds = false
skip-lint = false
[programs.localnet]
my_auction = "Bbnt2AVTcEgGwhAShxjwSFT6dUaSgM8kmKhtp3kvvnAD"

[registry]
# url = "https://api.apr.dev"
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
